"""Structured filter rules that gate trade entries.

Filter rules are generated by the auto-learning cycle (analyzer + Claude review)
and applied during backtesting and paper trading to skip low-quality signals.

Each rule has:
  - feature: the feature name from extract_features()
  - operator: >=, <=, ==, !=, >, <
  - threshold: numeric or string value
  - rule_type: "skip" (avoid trade) or "prefer" (boost confidence)
  - source: "analyzer" or "claude_review"
"""
from src.data.database import get_connection


def init_filter_rules_table(conn=None):
    """Create filter_rules table if it doesn't exist."""
    own_conn = conn is None
    if own_conn:
        conn = get_connection()
    cur = conn.cursor()
    cur.execute("""
        CREATE TABLE IF NOT EXISTS filter_rules (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            strategy TEXT NOT NULL,
            feature TEXT NOT NULL,
            operator TEXT NOT NULL,
            threshold TEXT NOT NULL,
            rule_type TEXT NOT NULL DEFAULT 'skip',
            effect_size REAL,
            source TEXT DEFAULT 'analyzer',
            rationale TEXT,
            active INTEGER DEFAULT 1,
            created_at TEXT DEFAULT (datetime('now'))
        )
    """)
    if own_conn:
        conn.commit()
        conn.close()


def save_filter_rules(strategy: str, rules: list[dict], source: str = "analyzer",
                      conn=None):
    """Save structured filter rules, deactivating old ones from the same source."""
    own_conn = conn is None
    if own_conn:
        conn = get_connection()
    cur = conn.cursor()

    # Deactivate previous rules from same source for this strategy
    cur.execute("""
        UPDATE filter_rules SET active = 0
        WHERE strategy = ? AND source = ?
    """, (strategy, source))

    for rule in rules:
        feature = rule.get("feature", "")
        operator = rule.get("operator", ">=")
        threshold = str(rule.get("threshold", ""))
        rule_type = rule.get("type", rule.get("rule_type", "skip"))
        effect_size = rule.get("effect_size")
        rationale = rule.get("rationale", rule.get("expected_impact", ""))

        if not feature or not threshold:
            continue

        cur.execute("""
            INSERT INTO filter_rules
            (strategy, feature, operator, threshold, rule_type, effect_size, source, rationale)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """, (strategy, feature, operator, threshold, rule_type,
              effect_size, source, rationale))

    if own_conn:
        conn.commit()
        conn.close()


def load_active_filters(strategy: str) -> list[dict]:
    """Load all active filter rules for a strategy."""
    conn = get_connection()
    cur = conn.cursor()

    # Check if filter_rules table exists
    cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='filter_rules'")
    if not cur.fetchone():
        conn.close()
        return []

    cur.execute("""
        SELECT feature, operator, threshold, rule_type, effect_size, rationale
        FROM filter_rules
        WHERE strategy = ? AND active = 1
        ORDER BY ABS(effect_size) DESC
    """, (strategy,))
    rows = cur.fetchall()
    conn.close()

    filters = []
    for row in rows:
        filters.append({
            "feature": row[0],
            "operator": row[1],
            "threshold": row[2],
            "rule_type": row[3],
            "effect_size": row[4],
            "rationale": row[5],
        })
    return filters


def apply_filters(features: dict, filters: list[dict]) -> tuple[bool, str]:
    """Check if a trade should be skipped based on active filter rules.

    Returns:
        (should_skip, reason) — True if trade should be skipped
    """
    for f in filters:
        if f["rule_type"] != "skip":
            continue

        feature_val = features.get(f["feature"])
        if feature_val is None:
            continue

        try:
            threshold = float(f["threshold"])
        except (ValueError, TypeError):
            threshold = f["threshold"]

        op = f["operator"]
        skip = False

        if op == ">=" and isinstance(feature_val, (int, float)):
            skip = feature_val >= threshold
        elif op == "<=" and isinstance(feature_val, (int, float)):
            skip = feature_val <= threshold
        elif op == ">" and isinstance(feature_val, (int, float)):
            skip = feature_val > threshold
        elif op == "<" and isinstance(feature_val, (int, float)):
            skip = feature_val < threshold
        elif op == "==":
            skip = str(feature_val) == str(threshold)
        elif op == "!=":
            skip = str(feature_val) != str(threshold)

        if skip:
            return True, f"Filter: {f['feature']} {op} {f['threshold']} ({f.get('rationale', '')})"

    return False, ""


def parse_analyzer_filters(suggested_filters: list[dict]) -> list[dict]:
    """Convert analyzer's suggested_filters to structured format."""
    structured = []
    for sf in suggested_filters:
        rule_text = sf.get("rule", "")
        feature = sf.get("feature", "")

        # Parse "feature >= threshold" or "feature <= threshold"
        operator = None
        threshold = None
        for op in [">=", "<=", ">", "<"]:
            if op in rule_text:
                parts = rule_text.split(op)
                if len(parts) == 2:
                    feature = parts[0].strip() if not feature else feature
                    try:
                        threshold = float(parts[1].strip())
                    except ValueError:
                        threshold = parts[1].strip()
                    operator = op
                break

        if feature and operator and threshold is not None:
            structured.append({
                "feature": feature,
                "operator": operator,
                "threshold": threshold,
                "type": "skip" if sf.get("effect_size", 0) < 0 else "prefer",
                "effect_size": sf.get("effect_size"),
                "rationale": sf.get("rationale", ""),
            })
    return structured


def parse_claude_filter_rules(filter_rules: list[dict]) -> list[dict]:
    """Convert Claude's filter_rules to structured format.

    Claude returns rules like:
      {"rule": "Skip when rsi_bull_divergence > 0.15", "type": "skip", ...}
    """
    structured = []
    for fr in filter_rules:
        rule_text = fr.get("rule", "")
        rule_type = fr.get("type", "skip")

        # Remove "Skip when " / "Prefer when " prefix
        clean = rule_text
        for prefix in ["Skip when ", "skip when ", "Prefer when ", "prefer when ",
                        "Skip if ", "skip if ", "Prefer if ", "prefer if "]:
            if clean.startswith(prefix):
                clean = clean[len(prefix):]
                break

        # Parse "feature op threshold"
        feature = None
        operator = None
        threshold = None
        for op in [">=", "<=", "!=", "==", ">", "<"]:
            if op in clean:
                parts = clean.split(op)
                if len(parts) == 2:
                    feature = parts[0].strip()
                    try:
                        threshold = float(parts[1].strip())
                    except ValueError:
                        threshold = parts[1].strip().strip("'\"")
                    operator = op
                break

        if feature and operator and threshold is not None:
            structured.append({
                "feature": feature,
                "operator": operator,
                "threshold": threshold,
                "type": rule_type,
                "effect_size": fr.get("effect_size"),
                "rationale": fr.get("expected_impact", ""),
            })
    return structured
